http:
  routers:
    lego-acme:
    #  && PathPrefix(`/.well-known/acme-challenge/{.*}`)
      rule: "PathPrefix(`/.well-known/acme-challenge`)"
      service: "lego-acme"
      entrypoints:
        - "web"
      priority: "2000"

    thelounge:
      rule: "Host(`thelounge.thegoos.cloud`)"
      service: "thelounge"
      tls: {}
      entrypoints:
        - "websecure"

  services:
    lego-acme:
      loadBalancer:
        servers:
          - url: "http://lego-acme.:80"

    thelounge:
      loadBalancer:
        servers:
          - url: "http://thelounge.:9000"

tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/certs/irc.thegoos.cloud.crt"
        keyFile: "/certs/irc.thegoos.cloud.key"
